name: First Work Flow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout
          uses: actions/checkout@v4

        - name: Welcome
          run: echo "my first githubactions"
          
        - name: listing
          run: ls -l

        - name: Read the file
          run: cat README.md