name: Multi-Job
on: push
jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:

        - name: unit
          run: echo "unit tests are complted" > results.txt

        - uses: actions/upload-artifact@v4
          with:
            name: unit-test results
            path: results.txt

    docker-build:
        needs: unit-testing
        runs-on: ubuntu-latest

        steps:
        - uses: actions/download-artifact@v4
          with:
            name: unit-test results

        - name: see the results
          run: cat results.txt

        - name: docker build
          run: echo "docker build completed"
    
    deploy:
        needs: docker-build
        runs-on: ubuntu-latest
        steps:
        
        - uses: actions/download-artifact@v4
          with:
            name: unit-test results

        - name: see the results
          run: cat results.txt
        
        - name: deploy
          run: echo "deploy to ecs"
