name: Multi-Job
on: push
jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
        - name: unit
          run: echo "unit tests are complted" >> unit-test.txt
        - uses: actions/upload-artifact@v4
          with:
            name: unit-test results
            path: unit-test.txt

    docker-build:
        needs: unit-testing
        runs-on: ubuntu-latest
        steps:
        - uses: actions/download-artifact@v4
          with:
            name: unit-test results
            path: unit-test.txt
        - name: see the results
          run: cat dragon.txt

        - name: docker build
          run: echo "docker build completed"
    
    deploy:
        needs: docker-build
        runs-on: ubuntu-latest
        steps:
        
        - uses: actions/download-artifact@v4
          with:
            name: unit-test results
            path: unit-test.txt
        
        - name: deploy
          run: echo "deploy to ecs"
